version: "3.1"
services:
    scheduler:
        volumes:
        - /home/<your username>/.google/credentials/google_credentials.json:/usr/local/airflow/.google/credentials/google_credentials.json:ro
        - /home/<your username>/steam-recommendations-DE-project/dbt:/usr/local/airflow/dbt:ro  
        

