version: "3.1"
services:
    scheduler:
        volumes:
        - /home/steam_project/.google/credentials/google_credentials.json:/usr/local/airflow/.google/credentials/google_credentials.json:ro
        - /home/steam_project/dbt:/usr/local/airflow/dbt:ro  
        - /home/steam_project/.dbt:/usr/local/airflow/.dbt:ro 

